try{
    Life.run()
}catch(Exception e){
    print("It's okay")
}